import importlib.util
import json
import subprocess
import sys
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
POST_WRITE_WARNINGS = ROOT / "plugin" / "hooks" / "scripts" / "post_write_warnings.py"

spec = importlib.util.spec_from_file_location("post_write_warnings", POST_WRITE_WARNINGS)
post_write_warnings = importlib.util.module_from_spec(spec)
assert spec.loader is not None
sys.modules["post_write_warnings"] = post_write_warnings
spec.loader.exec_module(post_write_warnings)


def payload(file_path, content, tool_name="Write"):
    tool_input = {"file_path": file_path}
    if tool_name == "Write":
        tool_input["content"] = content
    else:
        tool_input["new_string"] = content
    return {
        "hook_event_name": "PostToolUse",
        "tool_name": tool_name,
        "tool_input": tool_input,
    }


class PostWriteWarningsTests(unittest.TestCase):
    def run_hook(self, hook_payload):
        return subprocess.run(
            [sys.executable, str(POST_WRITE_WARNINGS)],
            input=json.dumps(hook_payload),
            text=True,
            capture_output=True,
            check=False,
        )

    def hook_output(self, completed):
        self.assertEqual(completed.returncode, 0)
        self.assertEqual(completed.stderr, "")
        return json.loads(completed.stdout)["hookSpecificOutput"]

    def context_for(self, file_path, content, tool_name="Write"):
        completed = self.run_hook(payload(file_path, content, tool_name=tool_name))
        return self.hook_output(completed)["additionalContext"]

    def test_secret_warning_uses_shared_secret_patterns(self):
        context = self.context_for(
            "src/config.py",
            'token = "github_pat_11AAAAAAA0abcdefghijklmnopqrstuvwxyz_ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdef"',
        )

        self.assertIn("[SECRET-GITHUB-PAT]", context)
        self.assertNotIn("github_pat_", context)

    def test_debug_warnings_preserve_legacy_patterns(self):
        context = self.context_for("src/app.ts", 'console.log("debug")\ndebugger')

        self.assertIn("[DEBUG-CONSOLE]", context)
        self.assertIn("[DEBUG-STATEMENT]", context)

    def test_python_print_warning_preserves_indented_match(self):
        context = self.context_for("src/app.py", '  print("hello")')

        self.assertIn("[DEBUG-PRINT]", context)

    def test_ci_workflow_change_warns(self):
        context = self.context_for(".github/workflows/lint.yml", "jobs:\n  test:\n")

        self.assertIn("[POST-CI-WORKFLOW]", context)

    def test_empty_ci_workflow_write_still_warns(self):
        context = self.context_for(".github/workflows/lint.yml", "")

        self.assertIn("[POST-CI-WORKFLOW]", context)

    def test_absolute_ci_workflow_path_warns(self):
        context = self.context_for("/workspace/project/.github/workflows/lint.yml", "jobs:\n  test:\n")

        self.assertIn("[POST-CI-WORKFLOW]", context)

    def test_migration_change_warns(self):
        context = self.context_for("db/migrations/001_create_users.sql", "CREATE TABLE users(id int);")

        self.assertIn("[POST-MIGRATION]", context)

    def test_empty_migration_write_still_warns(self):
        context = self.context_for("db/migrations/001_create_users.sql", "")

        self.assertIn("[POST-MIGRATION]", context)

    def test_generated_file_change_warns(self):
        context = self.context_for("src/generated/client.py", "# generated by tool\n")

        self.assertIn("[POST-GENERATED-FILE]", context)

    def test_todo_fixme_warns(self):
        context = self.context_for("src/app.py", "# TODO(owner): remove temporary branch\n")

        self.assertIn("[POST-TODO-FIXME]", context)

    def test_edit_uses_new_string(self):
        context = self.context_for("src/app.py", "breakpoint()", tool_name="Edit")

        self.assertIn("[DEBUG-BREAKPOINT]", context)

    def test_clean_change_has_no_output(self):
        completed = self.run_hook(payload("src/app.py", "def ok():\n    return 1\n"))

        self.assertEqual(completed.returncode, 0)
        self.assertEqual(completed.stdout, "")
        self.assertEqual(completed.stderr, "")

    def test_empty_regular_file_has_no_output(self):
        completed = self.run_hook(payload("src/app.py", ""))

        self.assertEqual(completed.returncode, 0)
        self.assertEqual(completed.stdout, "")
        self.assertEqual(completed.stderr, "")

    def test_post_tool_use_never_returns_permission_decision(self):
        output = post_write_warnings.run(
            payload("src/key.py", 'AWS_KEY = "AKIA1234567890ABCDEF"\nconsole.log("debug")')
        )

        self.assertIsNotNone(output)
        hook_output = output["hookSpecificOutput"]
        self.assertNotIn("permissionDecision", hook_output)
        self.assertNotIn("permissionDecisionReason", hook_output)

    def test_malformed_json_fails_open_without_content(self):
        completed = subprocess.run(
            [sys.executable, str(POST_WRITE_WARNINGS)],
            input="{invalid",
            text=True,
            capture_output=True,
            check=False,
        )

        self.assertEqual(completed.returncode, 0)
        self.assertEqual(completed.stdout, "")
        self.assertIn("post_write_warnings warning", completed.stderr)
        self.assertNotIn("invalid", completed.stderr)


if __name__ == "__main__":
    unittest.main()
