#!/usr/bin/env python3
"""Claude Code PostToolUse warnings for file writes."""

from __future__ import annotations

import fnmatch
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


SCRIPT_DIR = Path(__file__).resolve().parent
HOOKS_DIR = SCRIPT_DIR.parent
if str(HOOKS_DIR) not in sys.path:
    sys.path.insert(0, str(HOOKS_DIR))

from guard.decisions import dedupe_by_rule_id  # noqa: E402
from guard.secrets import detect_secrets  # noqa: E402


DEBUG_PATTERNS = [
    ("DEBUG-CONSOLE", "console.log/warn/error/debug/info", re.compile(r"console\.(?:log|warn|error|debug|info)\(")),
    ("DEBUG-STATEMENT", "debugger statement", re.compile(r"\bdebugger\b")),
    ("DEBUG-PRINT", "print()", re.compile(r"^\s*print\(", re.MULTILINE)),
    ("DEBUG-BREAKPOINT", "breakpoint()", re.compile(r"\bbreakpoint\(\)")),
    ("DEBUG-PDB", "pdb/ipdb debugger", re.compile(r"\bipdb\b|\bpdb\.set_trace")),
    ("DEBUG-RUBY", "binding.pry/irb", re.compile(r"\bbinding\.(?:pry|irb)\b")),
]

GENERATED_PATH_PATTERNS = [
    "**/generated/**",
    "**/*.generated.*",
    "**/vendor/**",
    "**/*.min.js",
    "**/*.min.css",
    "**/*.pb.go",
]
GENERATED_CONTENT_PATTERN = re.compile(
    r"(?:^|\n)\s*(?://|#|/\*)\s*(?:<auto-generated|auto-generated|generated by|code generated)\b",
    re.IGNORECASE,
)
CI_PATH_PATTERNS = [
    ".github/workflows/*.yml",
    ".github/workflows/*.yaml",
    ".gitlab-ci.yml",
    ".circleci/config.yml",
    "azure-pipelines.yml",
    "Jenkinsfile",
]
MIGRATION_PATH_PATTERN = re.compile(r"(?:^|/)(?:migrations?|versions?)(?:/|$)", re.IGNORECASE)
TODO_PATTERN = re.compile(r"\b(?:TODO|FIXME)\b")


@dataclass(frozen=True)
class PostWriteInput:
    tool_name: str
    file_path: str
    content: str


@dataclass(frozen=True)
class WarningFinding:
    rule_id: str
    message: str


def run(payload: dict[str, Any]) -> dict[str, object] | None:
    post_input = extract_post_write_input(payload)
    if post_input is None:
        return None

    findings = post_write_findings(post_input)
    if not findings:
        return None

    return warning_output(post_input.file_path, findings)


def extract_post_write_input(payload: dict[str, Any]) -> PostWriteInput | None:
    hook_event_name = payload.get("hook_event_name")
    if hook_event_name not in {None, "", "PostToolUse"}:
        return None

    tool_name = payload.get("tool_name")
    if tool_name not in {"Write", "Edit"}:
        return None

    tool_input = payload.get("tool_input")
    if not isinstance(tool_input, dict):
        return None

    raw_file_path = tool_input.get("file_path")
    if not isinstance(raw_file_path, str) or not raw_file_path:
        return None

    content_key = "content" if tool_name == "Write" else "new_string"
    content = tool_input.get(content_key)
    if not isinstance(content, str):
        return None

    return PostWriteInput(tool_name=tool_name, file_path=raw_file_path, content=content)


def post_write_findings(post_input: PostWriteInput) -> list[WarningFinding]:
    findings: list[WarningFinding] = []
    findings.extend(secret_findings(post_input.content))
    findings.extend(debug_findings(post_input.content))
    findings.extend(path_findings(post_input.file_path, post_input.content))
    findings.extend(todo_findings(post_input.content))
    return dedupe_by_rule_id(findings)


def secret_findings(content: str) -> list[WarningFinding]:
    return [
        WarningFinding(finding.rule_id, f"{finding.secret_type} detected; use environment variables or a secret manager.")
        for finding in detect_secrets(content)
    ]


def debug_findings(content: str) -> list[WarningFinding]:
    return [
        WarningFinding(rule_id, f"{label} detected; remove before committing production code.")
        for rule_id, label, pattern in DEBUG_PATTERNS
        if pattern.search(content)
    ]


def path_findings(file_path: str, content: str) -> list[WarningFinding]:
    normalized = normalize_path(file_path)
    findings: list[WarningFinding] = []

    if matches_any(normalized, GENERATED_PATH_PATTERNS) or GENERATED_CONTENT_PATTERN.search(content):
        findings.append(
            WarningFinding(
                "POST-GENERATED-FILE",
                "generated-file change detected; prefer regenerating from the source artifact.",
            )
        )

    if matches_any(normalized, CI_PATH_PATTERNS):
        findings.append(
            WarningFinding(
                "POST-CI-WORKFLOW",
                "CI workflow change detected; verify jobs, permissions, and required checks.",
            )
        )

    if MIGRATION_PATH_PATTERN.search(normalized):
        findings.append(
            WarningFinding(
                "POST-MIGRATION",
                "migration change detected; verify reversibility and test against realistic data.",
            )
        )

    return findings


def todo_findings(content: str) -> list[WarningFinding]:
    if TODO_PATTERN.search(content):
        return [WarningFinding("POST-TODO-FIXME", "TODO/FIXME marker detected; ensure it has owner/context before committing.")]
    return []


def normalize_path(file_path: str) -> str:
    normalized = file_path.replace("\\", "/")
    while normalized.startswith("./"):
        normalized = normalized[2:]
    return normalized


def matches_any(path: str, patterns: list[str]) -> bool:
    candidates = {path, f"./{path}"}
    if path.startswith("/"):
        candidates.add(path.lstrip("/"))
    return any(
        fnmatch.fnmatch(candidate, pattern) or fnmatch.fnmatch(candidate, f"*/{pattern}")
        for candidate in candidates
        for pattern in patterns
    )


def warning_output(file_path: str, findings: list[WarningFinding]) -> dict[str, object]:
    details = " ".join(f"[{finding.rule_id}] {finding.message}" for finding in findings)
    return {
        "hookSpecificOutput": {
            "hookEventName": "PostToolUse",
            "additionalContext": f"Post-write warnings for {file_path}: {details}",
        }
    }


def main() -> int:
    try:
        raw_input = sys.stdin.read()
        if not raw_input.strip():
            return 0

        payload = json.loads(raw_input)
        if not isinstance(payload, dict):
            print("post_write_warnings warning: hook payload must be a JSON object", file=sys.stderr)
            return 0

        output = run(payload)
        if output is not None:
            print(json.dumps(output, separators=(",", ":")))
        return 0
    except Exception as exc:  # noqa: BLE001 - hook must fail open without exposing content.
        print(f"post_write_warnings warning: internal error: {exc}", file=sys.stderr)
        return 0


if __name__ == "__main__":
    sys.exit(main())
